### ISSUE TITLE
Specific NPCs don't deal damage in Horde Gamemode.

### ISSUE THREAD

**Issue by Orgamorsh** [tpan496/Horde#123]
I swear I have tried everything. I uninstalled everything but the conflicting mods. I've also tried resetting Gmod to factory and it still doesn't work. Everything works fine with normal sandbox.

The NPCs from Bio-Annihilation II don't deal damage.

NPCs using Arc9 guns don't deal damage, but do with default.

Console has no errors.

**Comment by The1337Gh0st** [comment]
it's likely these addons have an issue with horde itself (since it only really works with addons that were set up properly for it), you'll probably have to extract it yourself and see if it has anything that might be causing a conflict
