### ISSUE TITLE
Chat Commands from addons don't work

### ISSUE THREAD

**Issue by timothybvf** [tpan496/Horde#21]
For some reason addons that have chat commands aren't working in the gamemode.

**Comment by tpan496** [comment]
that might have been blocked by my function hook. will check later.

**Comment by tpan496** [comment]
I don't actually know how to prevent this from happening, other than removing my "PlayerSay" hook. Will investigate more.

**Comment by Ultimeit** [comment]
@tpan496 remove this line https://github.com/tpan496/Horde/blob/f700d39fc781f9528868815eef3b205bc86709d5/gamemode/sv_commands.lua#L223

**Comment by tpan496** [comment]
patched
