### ISSUE TITLE
Beeing able to "Vote" for ....

### ISSUE THREAD

**Issue by Pdzly** [tpan496/Horde#25]
... endless mode (enable/disable)
... faster end of the bugged round (like stuck in a wall) and that this has a "cooldown" like for 60 seconds that no one can spam that

And as "Admin" (ulx or else) "force" start and stop or pause

**Comment by tpan496** [comment]
Voting endless wouldn't be an option, you either start the server in endless or not.
Force start is already in the game. It's not possible to stop the game in mid-wave, I mean it's literally like cheating right.
Voting for the end of a bugged round also sounds really weird to me. Like players can just abuse it in a lot of different ways.
