### ISSUE TITLE
Horde spawn near player owned entities

### ISSUE THREAD

**Issue by Ultimeit** [tpan496/Horde#30]
Zombies can respawn near player owned entities, e.g. turrets. That's very annoying when zombie respawns near your turrets and instantly kills them.

**Comment by tpan496** [comment]
This is a tricky issue. I've thought about adding this, but if there are too many sentries around then it's possible for zombies to not spawn at all.

**Comment by Ultimeit** [comment]
How about making a ConVar for minimal distance between zombie spawn and player owned entity?

Another random though is: retrying spawnpoint search with ignoring player owned entities, if no suitable spawnpoint was found on first attempt

**Comment by tpan496** [comment]
> How about making a ConVar for minimal distance between zombie spawn and player owned entity? This won't solve possible issue completely, but will allow server owners to tweak it along with changes to player entity limits.
> 
> Another random though is: retrying spawnpoint search with ignoring player owned entities, if no suitable spawnpoint was found on first attempt

The first approach seems reasoanble. I'll think about this.

**Comment by tpan496** [comment]
now that turrets are a lot more stable (and tankier) I think we wouldn't need to worry about this anymore.
