### ISSUE TITLE
Consider changing default engineer available turret

### ISSUE THREAD

**Issue by Ultimeit** [tpan496/Horde#31]
Default gmod built-in turret entity is simply bad, that's it. Imo, replacing it with some kind of lua-based turret would be much better in terms of gameplay.
Ideally - custom turret base specifically for Horde gamemode.
Alternative - [This](https://steamcommunity.com/sharedfiles/filedetails/?id=1672711003) workshop addon seems to be pretty good, it also has repair/ammo refill mechanics. I'm not sure if these are downsides or upsides, but: turrets cannot be moved, repair/ammo refill kits are not SWEP's (they are entities).

[These](https://steamcommunity.com/sharedfiles/filedetails/?id=524738501) turrets looks very nice, especially their deployment animation, but I doubt they will be any good as is with Horde gamemode.

**Comment by Ultimeit** [comment]
Not sure how I managed to miss [this addon](https://steamcommunity.com/sharedfiles/filedetails/?id=2148085542) previously, but it looks awesome :O

**Comment by BishY1** [comment]
The scrap turret addon requires hl2, css and hl2 ep 2, I don't think it works since people have not bought those games

**Comment by Ultimeit** [comment]
Yeah, scrap turret is no longer my favorite after I found pack with flamethrower turret anyway.

**Comment by tpan496** [comment]
might add new turret variants in the future. closing this for now.
