### ISSUE TITLE
VJ NPCs one-shotting turrets

### ISSUE THREAD

**Issue by tpan496** [tpan496/Horde#33]
Like why. Doesn't make any sense.

**Comment by Ultimeit** [comment]
@tpan496 https://github.com/DrVrej/VJ-Base/blob/16024a454ca950ee7ff321c5649afcdcf729e081/lua/autorun/vj_globals.lua#L251
This function name is a bit suspicious >.>

**Comment by tpan496** [comment]
> @tpan496 https://github.com/DrVrej/VJ-Base/blob/16024a454ca950ee7ff321c5649afcdcf729e081/lua/autorun/vj_globals.lua#L251
> This function name is a bit suspicious >.>

...shit

**Comment by Ultimeit** [comment]
@tpan496 just override it and that's it somewhere in serverside gamemode file. Though I'd prefer lua based turrets anyway.
function VJ_DestroyCombineTurret() end

**Comment by tpan496** [comment]
patched
