### ISSUE TITLE
IsAdmin() missing in some commands/network requests

### ISSUE THREAD

**Issue by tpan496** [tpan496/Horde#35]

**Comment by tpan496** [comment]
@Ultimeit actually what are some of the things/examples that you mentioned are missing checks? I checked the commands section and they are protected.

**Comment by Ultimeit** [comment]
@tpan496 https://github.com/tpan496/Horde/blob/f700d39fc781f9528868815eef3b205bc86709d5/gamemode/sh_enemy.lua#L332
https://github.com/tpan496/Horde/blob/be01b39446c98d8ec717da95f9d5858613c2573a/gamemode/sh_item.lua#L603
https://github.com/tpan496/Horde/blob/525471d135eaedcec7121269586e0ada939164ab/gamemode/sh_class.lua#L159

**Comment by tpan496** [comment]
👍 patched
*Ah, another fellow Exile?*

**Comment by Ultimeit** [comment]
_Still sane, Exile? ( ͡° ͜ʖ ͡°)_
