### ISSUE TITLE
AR2 Ball Pushing Players Around

### ISSUE THREAD

**Issue by tpan496** [tpan496/Horde#38]

**Comment by tpan496** [comment]
might be fixed by SetTeam(), need to check on this tho

**Comment by Ultimeit** [comment]
Not fixed. Bullet collision wasn't fixed too.

**Comment by tpan496** [comment]
> Not fixed. Bullet collision wasn't fixed too.

what is the gamemode that you mentioned where bullets/balls won't collide with players?

**Comment by Ultimeit** [comment]
This gamemode doesn't have combine balls 208.103.169.70:27025, though combine balls can be fixed via lua by at least 2 ways:
1. [Custom collision rules for players.](https://wiki.facepunch.com/gmod/GM:ShouldCollide)
2. Creating your own entity **[prop_combine_ball](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/server/hl2/prop_combine_ball.cpp)** to override default one. Never tried doing that with combine ball, but works fine with some other built-in entities.
3. Removing AR2 or removing secondary fire from AR2 (This isn't a fix though)

**Comment by Ultimeit** [comment]
Also, just noticed, you was using ply:SetTeam(1), but does such team even exist in gamemode?

**Comment by Ultimeit** [comment]
This should fix both issues hopefully https://github.com/tpan496/Horde/pull/41

**Comment by tpan496** [comment]
just verified that this is fixed. thanks man!
