### ISSUE TITLE
Turrets can be knocked down using Bayonet

### ISSUE THREAD

**Issue by tpan496** [tpan496/Horde#40]
fuck

**Comment by Ultimeit** [comment]
This one is somewhat tricky to fix [without editing ArcCW files](https://github.com/HaodongMo/ArcCW/blob/b221673ee7c71c47f4d748dd7ec522e3868bcceb/lua/weapons/arccw_base/sh_bash.lua#L223). Probably best all-round solution is utilizing [newly added hook](https://wiki.facepunch.com/gmod/GM:OnPlayerPhysicsDrop) and [disable turret motion](https://wiki.facepunch.com/gmod/PhysObj:EnableMotion) when player drops it. In theory this should make turret placement less clunky as well, though I'm not sure. Also don't forget to check if turret is on the ground before disabling motion. [Entity:OnGround](https://wiki.facepunch.com/gmod/Entity:OnGround) might work, if not - just use trace.

Another option is overriding ArcCW function, though might cause issues if they will decide to update that function:
`local wpn = weapons.GetStored("arccw_base")
function wpn:MeleeAttack(melee2)
[*insert copypasted and edited function here*](https://github.com/HaodongMo/ArcCW/blob/b221673ee7c71c47f4d748dd7ec522e3868bcceb/lua/weapons/arccw_base/sh_bash.lua#L116)
end
`

Btw, a bit offtopic, but I'd suggest relying on [trace](https://wiki.facepunch.com/gmod/util.TraceLine) for entity purchases as well.

**Comment by tpan496** [comment]
This should be fixed in 9ed58fc. Using `SetMotion(false` is sufficient. There is a short delay (0.5s) where you might still be able to knock down turrets, but I think that is negligible. This also makes turrets placements smoother in general.
