### ISSUE TITLE
Suggestion: Enabling lag compensation for NPC's spawned by Horde gamemode

### ISSUE THREAD

**Issue by Ultimeit** [tpan496/Horde#42]
Honestly, never ever bothered using [this](https://wiki.facepunch.com/gmod/Entity:SetLagCompensated). I also have no idea on how to test properly if this is a good change or not.
Currently, without lag compensation, when playing on server sometimes my bullets deal no damage, despite leaving blood decal as if I managed to successfully hit enemy. This mostly noticeable when trying to hit headcrabs.

**Comment by Pdzly** [comment]
It could be that it still hits BUT he has more hp than you think it scales with the difficulty and wave and your settings on wave 3 or more on standard settings headcrabs needs more hits than normal

**Comment by Pdzly** [comment]
![image](https://user-images.githubusercontent.com/34943569/110666273-74a03c80-81c9-11eb-886a-959b47120a7d.png)

That is it on or off?
And does it still happen?
Does something come up in the console?
And did you look at the Servers FPS? and your ping etc.

**Comment by tpan496** [comment]
done, seems fine
