### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by tpan496** [tpan496/Horde#43]

**Comment by Pdzly** [comment]
Localization like Language or Localization of places ?

**Comment by tpan496** [comment]
> Localization like Language or Localization of places ?

language

**Comment by tpan496** [comment]
> Can i help you there ? i can good german :)

sure, help is appreciated! I will let you know when I start working on this part.

**Comment by Blueberryy** [comment]
I can help too

**Comment by tpan496** [comment]
> I can help too
👍

**Comment by Kazahist** [comment]
Me too

**Comment by Pdzly** [comment]
I can safely say you have enough support for that xd Cool to see this support @everyone

**Comment by BishY1** [comment]
I can add the spanish language if u want

**Comment by Kazahist** [comment]
i can translate into a ru and kz
because i am kazah
