### ISSUE TITLE
Turret placement abuse

### ISSUE THREAD

**Issue by Ultimeit** [tpan496/Horde#54]
:DropToFloor() won't work if turret dropped from high enough height
![image](https://user-images.githubusercontent.com/49292935/110574118-682dcc80-8154-11eb-98af-8e4a8b09c498.png)

**Comment by tpan496** [comment]
yeah prob should use Trace()

**Comment by tpan496** [comment]
6828aec687d371900d1c84e866c8c52223486d6c

Now players also won't be able to drop turrets from a place too far. In that case, turrets will just fall over.
