### ISSUE TITLE
Perks: Ghost

### ISSUE THREAD

**Issue by tpan496** [tpan496/Horde#67]
The Ghost class is designed to be excelled in taking down single target enemies (e.g. elites, boss). Ghost players should be awarded for their precision.

**Comment by Ultimeit** [comment]
> Projectile Attack Hits deal 20% less Damage to targets at the start of their movement, dealing up to 60% more Damage to targets as the projectile travels farther.
*cough* Deadeye class *cough*

**Comment by tpan496** [comment]
done
