### ISSUE TITLE
Custom configs can't be loaded

### ISSUE THREAD

**Issue by Fakas** [tpan496/Horde#74]
Custom config Lua files can't be loaded it seems, because the relevant calls to AddCSLuaFile and include fail to reference the gamemode directory. Hopefully this is a simple fix, but I'm having some trouble compiling the addon locally.

**Comment by tpan496** [comment]
Custom Config Lua can be loaded. You are putting them in the wrong place. Check the front page.

**Comment by Fakas** [comment]
Issue was that I had put the relevant config in server.cfg rather than autoexec.cfg, closing.
