### ISSUE TITLE
Solar Seal

### ISSUE THREAD

**Issue by OceanRainbowSparkle** [tpan496/Horde#81]
A friend and I play horde, he hosts and builds crazy cool configs. I wanted to play the new artificer subclass but we found that the solar seal wasn't given to me, and my friend couldn't even spawn it. He even went so far as to download the mainfile from here and install it directly by hand, but it still didn't work.

**Comment by tpan496** [comment]
if you have errors you can post them. solar seal works fine on all the servers i've been to.
