### ISSUE TITLE
Cremator's Firestorm's description is incorrect / infinite buildup for Burst

### ISSUE THREAD

**Issue by The1337Gh0st** [tpan496/Horde#90]
Cremator's Firestorm states that Burst causes Blast damage, yet it actually causes Fire damage. This means that it can lead to infinite chains if you gain a big enough Fire damage boost, thus killing anything instantly.

https://github.com/tpan496/Horde/blob/main/gamemode/perks/cremator/cremator_firestorm.lua

https://github.com/tpan496/Horde/blob/main/gamemode/status/debuff/sv_burst.lua

**Comment by tpan496** [comment]
fixed
